version: '3.8'

services:
  cron-url:
    image: nghiepit/cron-url
    environment:
      TZ: Asia/Ho_Chi_Minh
      CRON_URLS: |
        * * * * * * https://www.gstatic.com/generate_204
    restart: unless-stopped